'use client'

import { useMemo, useState } from 'react'
import Image from 'next/image'
import { ArrowRight, Check, CircleUserRound, Heart, Menu, Minus, PackageCheck, Plus, Search, ShoppingBag, Sparkles, Truck, X } from 'lucide-react'
import { Button } from '@/components/ui/button'

type Product = { id: string; name: string; description: string; price: number; compareAt: number; tag: string; image: string }
type CartItem = Product & { quantity: number }
type View = 'home' | 'shop' | 'product' | 'cart' | 'checkout' | 'account' | 'orders'

const products: Product[] = [
  { id: 'salt', name: 'Himalayan Salt & Pepper', description: 'Clean, savoury and quietly addictive.', price: 249, compareAt: 299, tag: 'Bestseller', image: '/mr-makhana-salted.png' },
  { id: 'saffron', name: 'Saffron Pepper', description: 'Warm, golden and a little bold.', price: 279, compareAt: 329, tag: 'New', image: '/mr-makhana-saffron.png' },
  { id: 'herb', name: 'Herb & Lime', description: 'Bright with a fresh finish.', price: 269, compareAt: 319, tag: 'Light & zesty', image: '/mr-makhana-herb.png' },
  { id: 'cocoa', name: 'Cocoa Cinnamon', description: 'A better kind of sweet tooth.', price: 289, compareAt: 339, tag: 'Limited batch', image: '/mr-makhana-cocoa.png' },
]

export default function Page() {
  const [view, setView] = useState<View>('home')
  const [selected, setSelected] = useState(products[0])
  const [cart, setCart] = useState<CartItem[]>([])
  const [menuOpen, setMenuOpen] = useState(false)
  const [confirmed, setConfirmed] = useState(false)
  const total = useMemo(() => cart.reduce((sum, item) => sum + item.price * item.quantity, 0), [cart])
  const count = cart.reduce((sum, item) => sum + item.quantity, 0)
  const go = (next: View) => { setView(next); setMenuOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const add = (product: Product, quantity = 1) => setCart((items) => items.some((item) => item.id === product.id) ? items.map((item) => item.id === product.id ? { ...item, quantity: item.quantity + quantity } : item) : [...items, { ...product, quantity }])
  const change = (id: string, delta: number) => setCart((items) => items.map((item) => item.id === id ? { ...item, quantity: Math.max(0, item.quantity + delta) } : item).filter((item) => item.quantity > 0))
  const openProduct = (product: Product) => { setSelected(product); go('product') }

  return <div className="min-h-screen bg-[#faf8f3] text-[#173a2b]">
    <div className="bg-[#173a2b] px-4 py-3 text-center text-[10px] font-bold uppercase tracking-[0.24em] text-[#f1cf8a]">Free shipping on orders over ₹599 <span className="mx-3 text-[#b7663a]">•</span> Small batch. Big crunch.</div>
    <header className="border-b border-[#173a2b]/10 bg-[#faf8f3]">
      <div className="mx-auto flex h-24 max-w-[1440px] items-center justify-between px-5 lg:px-14">
        <button className="lg:hidden" aria-label="Open menu" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button>
        <button onClick={() => go('home')} className="flex items-center gap-3" aria-label="MR Makhana home"><span className="relative grid size-12 place-items-center rounded-full border border-[#b7663a] bg-[#f3eadc] text-[13px] font-sans font-bold tracking-[-0.08em] text-[#b7663a] before:absolute before:inset-1 before:rounded-full before:border before:border-[#b7663a]/35">MR</span><span className="text-xl font-serif font-semibold tracking-tight text-[#173a2b]">MR Makhana</span></button>
        <nav className={`${menuOpen ? 'absolute left-0 right-0 top-[145px] z-30 flex border-b border-[#173a2b]/10 bg-[#faf8f3] px-6 py-6' : 'hidden'} flex-col gap-5 text-sm font-semibold lg:static lg:flex lg:flex-row lg:bg-transparent lg:p-0`}><button onClick={() => go('shop')}>Shop</button><button onClick={() => go('home')}>Our story</button><button onClick={() => go('orders')}>Track order</button><button onClick={() => go('home')}>FAQs</button></nav>
        <div className="flex items-center gap-4"><button className="hidden lg:block" aria-label="Search"><Search /></button><button aria-label="Account" onClick={() => go('account')}><CircleUserRound /></button><button aria-label="Cart" className="relative rounded-full bg-[#f3eadc] p-3" onClick={() => go('cart')}><ShoppingBag /><span className="absolute -right-1 -top-1 grid size-5 place-items-center rounded-full bg-[#b7663a] text-[10px] text-white">{count}</span></button></div>
      </div>
    </header>
    {view === 'home' && <Home go={go} openProduct={openProduct} add={add} />}
    {view === 'shop' && <Shop openProduct={openProduct} add={add} />}
    {view === 'product' && <ProductDetail product={selected} go={go} add={add} />}
    {view === 'cart' && <Cart cart={cart} total={total} go={go} change={change} />}
    {view === 'checkout' && <Checkout total={total} confirmed={confirmed} setConfirmed={setConfirmed} go={go} />}
    {view === 'account' && <Account go={go} />}
    {view === 'orders' && <Orders go={go} />}
    <Footer go={go} />
  </div>
}

function Home({ go, openProduct, add }: { go: (v: View) => void; openProduct: (p: Product) => void; add: (p: Product) => void }) { return <main>
  <section className="mx-auto grid max-w-[1440px] items-center gap-12 px-5 py-14 lg:grid-cols-[0.84fr_1.16fr] lg:px-14 lg:py-24"><div><p className="mb-7 inline-flex items-center gap-2 rounded-full border border-[#d8c5a9] px-5 py-3 text-[11px] font-bold uppercase tracking-[0.24em] text-[#b7663a]"><Sparkles /> India&apos;s favourite better crunch</p><h1 className="max-w-xl font-serif text-6xl leading-[.9] tracking-[-.06em] md:text-8xl">Good mood.<br /><span className="text-[#b7663a]">Great crunch.</span></h1><p className="mt-8 max-w-lg text-lg leading-8 text-[#65756d]">Premium roasted makhana made with simple ingredients, big flavour and absolutely no compromise on the little joys.</p><div className="mt-9 flex flex-wrap gap-4"><Button onClick={() => go('shop')} className="h-14 rounded-full bg-[#173a2b] px-8 text-base text-white hover:bg-[#24513d]">Shop the crunch <ArrowRight data-icon="inline-end" /></Button><Button variant="outline" className="h-14 rounded-full border-[#d8c5a9] px-8 text-base" onClick={() => document.getElementById('why')?.scrollIntoView({ behavior: 'smooth' })}>Why makhana? <ArrowRight data-icon="inline-end" /></Button></div><div className="mt-14 flex gap-7 border-t border-[#173a2b]/15 pt-5 text-sm text-[#65756d]"><span>Naturally light</span><span>✓ Always roasted</span></div></div><div className="relative aspect-[1.15] overflow-hidden rounded-[2rem] bg-[#d8c5a9]"><Image src="/mr-makhana-hero-premium.png" alt="MR Makhana roasted foxnuts" fill priority className="object-cover"/><span className="absolute right-7 top-7 grid size-28 rotate-6 place-items-center rounded-full bg-[#f1cf8a] p-5 text-center text-[10px] font-bold uppercase leading-4 tracking-[0.18em] text-[#173a2b]">Made for<br />the mindful</span><div className="absolute bottom-5 left-5 right-5 flex items-end justify-between text-white"><div><p className="text-[10px] font-bold uppercase tracking-[0.3em] text-[#f1cf8a]">The signature collection</p><p className="mt-2 font-serif text-4xl">Roast. Toss. Repeat.</p></div><span className="rounded-full border border-white/40 px-4 py-2 text-xs">100% fox nuts</span></div></div></section>
  <section className="border-y border-[#173a2b]/10 bg-[#f3eadc] px-5 py-7 lg:px-14"><div className="mx-auto grid max-w-[1440px] grid-cols-2 gap-5 text-center text-[10px] font-bold uppercase tracking-[0.2em] text-[#65756d] md:grid-cols-4"><span>◌ Plant-powered</span><span>✦ Small batch</span><span>◇ Freshly packed</span><span>▱ Pan-India delivery</span></div></section>
  <section className="mx-auto max-w-[1440px] px-5 py-20 lg:px-14 lg:py-28"><div className="mb-10 flex items-end justify-between"><div><p className="mb-4 text-[11px] font-bold uppercase tracking-[0.3em] text-[#b7663a]">The good stuff</p><h2 className="font-serif text-5xl tracking-[-.05em]">Find your flavour</h2><p className="mt-4 text-lg text-[#65756d]">Four small-batch roasts. One seriously satisfying snack break.</p></div><button className="hidden font-semibold text-[#b7663a] md:block" onClick={() => go('shop')}>View all snacks →</button></div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{products.map((product) => <ProductCard key={product.id} product={product} openProduct={openProduct} add={add} />)}</div></section>
  <section id="why" className="bg-[#173a2b] px-5 py-20 text-[#faf8f3] lg:px-14 lg:py-28"><div className="mx-auto max-w-[1440px]"><p className="mb-10 max-w-xl text-lg leading-8 text-white/60">We keep it simple: honest ingredients, thoughtful roasting and flavour that makes healthy feel like a treat.</p><div className="grid gap-10 border-t border-white/20 pt-14 md:grid-cols-3">{[['01','A lighter kind of more','Makhana is naturally light, with the kind of airy crunch that keeps you coming back.'],['02','Roasted, never rushed','Every batch is slow-roasted in small quantities for a deeper flavour and better bite.'],['03','Flavour with a point of view','From familiar comfort to playful twists, each seasoning is made to be remembered.']].map(([n,t,c]) => <div key={n}><p className="font-serif text-5xl text-[#f1cf8a]">{n}</p><h3 className="mt-7 text-xl font-bold">{t}</h3><p className="mt-4 leading-7 text-white/60">{c}</p></div>)}</div></div></section>
  <section className="mx-auto grid max-w-[1440px] items-center gap-10 px-5 py-20 lg:grid-cols-2 lg:px-14 lg:py-28"><div className="relative aspect-[.9] overflow-hidden rounded-[2rem]"><Image priority src="/mr-makhana-hero-premium.png" alt="A warm MR Makhana snack moment" fill sizes="(max-width: 1024px) 100vw, 58vw" className="hero-image object-cover object-[center_58%]"/></div><div className="lg:px-10"><p className="text-[11px] font-bold uppercase tracking-[0.3em] text-[#b7663a]">Snack smarter</p><h2 className="mt-5 font-serif text-5xl leading-[.98] tracking-[-.05em]">A handful of goodness, in every bowl.</h2><p className="mt-7 text-lg leading-8 text-[#65756d]">Grown in the wetlands of Bihar, makhana has been loved for generations. We bring it to your shelf with a modern twist — and a lot of care.</p><div className="mt-10 grid grid-cols-3 gap-4 border-t border-[#173a2b]/15 pt-6"><div><b className="font-serif text-3xl">4g</b><p className="mt-1 text-xs text-[#65756d]">protein</p></div><div><b className="font-serif text-3xl">100%</b><p className="mt-1 text-xs text-[#65756d]">vegetarian</p></div><div><b className="font-serif text-3xl">0%</b><p className="mt-1 text-xs text-[#65756d]">preservatives</p></div></div></div></section>
  <section className="bg-[#f3eadc] px-5 py-20 lg:px-14 lg:py-28"><div className="mx-auto max-w-[1440px]"><p className="text-center text-[11px] font-bold uppercase tracking-[0.3em] text-[#b7663a]">The nice things people say</p><h2 className="mt-5 text-center font-serif text-5xl tracking-[-.05em]">A snack break worth talking about.</h2><div className="mt-14 grid gap-5 md:grid-cols-3">{[['“The crunch is unreal. Finally a desk snack that doesn’t make me feel like I need a nap.”','— Rhea, Mumbai'],['“Saffron Pepper is my new movie-night ritual. The seasoning is so thoughtful.”','— Arjun, Bengaluru'],['“The packaging is beautiful enough to gift, and the product is even better.”','— Naina, Delhi']].map(([quote,by], i) => <article key={by} className={`rounded-[1.5rem] p-8 lg:p-10 ${i === 1 ? 'bg-[#173a2b] text-[#faf8f3]' : 'bg-[#faf8f3]'}`}><p className="text-2xl leading-8">★★★★★</p><p className="mt-8 font-serif text-2xl leading-8">{quote}</p><p className="mt-10 text-xs font-bold uppercase tracking-[0.2em] opacity-60">{by}</p></article>)}</div></div></section>
  <section className="mx-auto max-w-[1440px] px-5 py-20 lg:px-14 lg:py-28"><p className="text-[11px] font-bold uppercase tracking-[0.3em] text-[#b7663a]">Follow the crunch</p><h2 className="mt-5 font-serif text-5xl tracking-[-.05em]">Found in good company.</h2><p className="mt-4 text-lg text-[#65756d]">Tag @mrm akhana for a chance to be featured.</p><div className="mt-12 grid grid-cols-2 gap-4 md:grid-cols-4"><div className="relative aspect-square overflow-hidden rounded-[1.5rem]"><Image src="/mr-makhana-salted.png" alt="Seasoned makhana bowls" fill className="object-cover"/></div><div className="relative aspect-square overflow-hidden rounded-[1.5rem]"><Image src="/mr-makhana-hero-premium.png" alt="MR Makhana pouch" fill className="object-cover"/></div><div className="relative aspect-square overflow-hidden rounded-[1.5rem]"><Image src="/mr-makhana-saffron.png" alt="Saffron Pepper makhana" fill className="object-cover"/></div><div className="relative aspect-square overflow-hidden rounded-[1.5rem]"><Image src="/mr-makhana-cocoa.png" alt="Cocoa Cinnamon makhana" fill className="object-cover"/></div></div></section>
  <section className="bg-[#f3eadc] px-5 py-16 lg:px-14"><div className="mx-auto flex max-w-[1440px] flex-col items-start justify-between gap-8 md:flex-row md:items-center"><div><p className="text-[11px] font-bold uppercase tracking-[0.3em] text-[#b7663a]">A good thing in your inbox</p><h2 className="mt-4 font-serif text-4xl">Get first dibs on new flavours.</h2></div><form className="flex w-full max-w-xl gap-3" onSubmit={(e) => e.preventDefault()}><input type="email" required placeholder="Your email address" className="min-w-0 flex-1 rounded-full border border-[#d8c5a9] bg-[#faf8f3] px-6 py-4 outline-none focus:border-[#b7663a]"/><Button className="rounded-full bg-[#173a2b] px-7 text-white">Join us</Button></form></div></section>
</main> }

function ProductCard({ product, openProduct, add }: { product: Product; openProduct: (p: Product) => void; add: (p: Product) => void }) { return <article className="product-card group reveal"><button className="relative block aspect-square w-full overflow-hidden rounded-[1.5rem] bg-[#eee6d8]" onClick={() => openProduct(product)}><Image src={product.image} alt={product.name} fill sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 25vw" className="product-image object-cover object-center transition-transform duration-700 group-hover:scale-105"/><span className="absolute left-4 top-4 rounded-full bg-[#faf8f3] px-4 py-2 text-[10px] font-bold uppercase tracking-[0.2em] text-[#6d5d4c]">{product.tag}</span><span className="absolute bottom-4 right-4 grid size-14 place-items-center rounded-full bg-[#faf8f3] text-2xl">+</span></button><div className="flex items-start justify-between gap-3 px-1 pt-5"><button className="text-left" onClick={() => openProduct(product)}><h3 className="font-serif text-2xl">{product.name}</h3><p className="mt-1 text-sm text-[#7c887f]">{product.description}</p></button><div className="text-right"><b className="text-lg">₹{product.price}</b><s className="block text-xs text-[#9ba19c]">₹{product.compareAt}</s></div></div><button className="mt-4 flex items-center gap-2 text-sm font-bold text-[#b7663a]" onClick={() => add(product)}>Add to bag <ArrowRight /></button></article> }

function Shop({ openProduct, add }: { openProduct: (p: Product) => void; add: (p: Product) => void }) { return <main className="mx-auto max-w-[1440px] px-5 py-16 lg:px-14 lg:py-24"><p className="mb-4 text-[11px] font-bold uppercase tracking-[0.3em] text-[#b7663a]">The good stuff</p><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><h1 className="font-serif text-6xl tracking-[-.06em]">Find your flavour</h1><p className="max-w-sm text-[#65756d]">Four small-batch roasts. One seriously satisfying snack break.</p></div><div className="mt-12 flex gap-3 overflow-x-auto border-b border-[#173a2b]/10 pb-5 text-sm"><button className="rounded-full bg-[#173a2b] px-5 py-3 text-white">All snacks</button><button className="rounded-full border border-[#d8c5a9] px-5 py-3">Best sellers</button><button className="rounded-full border border-[#d8c5a9] px-5 py-3">Bundles</button></div><div className="mt-10 grid gap-x-6 gap-y-14 sm:grid-cols-2 lg:grid-cols-4">{products.map((p) => <ProductCard key={p.id} product={p} openProduct={openProduct} add={add} />)}</div></main> }

function ProductDetail({ product, go, add }: { product: Product; go: (v: View) => void; add: (p: Product, q?: number) => void }) { const [qty, setQty] = useState(1); return <main className="mx-auto grid max-w-[1440px] gap-12 px-5 py-14 lg:grid-cols-2 lg:px-14 lg:py-24"><div className="relative aspect-square overflow-hidden rounded-[2rem] bg-[#eee6d8]"><Image src={product.image} alt={product.name} fill sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover object-center"/></div><div className="flex flex-col justify-center lg:px-12"><p className="text-[11px] font-bold uppercase tracking-[0.3em] text-[#b7663a]">MR Makhana · 80 g</p><h1 className="mt-5 font-serif text-6xl leading-none tracking-[-.06em]">{product.name}</h1><p className="mt-6 text-xl leading-8 text-[#65756d]">{product.description} Made for slow moments and better snack breaks.</p><p className="mt-8 text-3xl font-semibold">₹{product.price}</p><div className="my-9 border-y border-[#173a2b]/15 py-6 text-sm leading-7 text-[#65756d]">Lotus seeds, cold-pressed oil and seasoning. No preservatives, no palm oil, no drama.</div><div className="flex gap-3"><div className="flex items-center rounded-full border border-[#d8c5a9]"><button className="grid size-12 place-items-center" onClick={() => setQty(Math.max(1, qty - 1))}><Minus /></button><span className="w-8 text-center font-bold">{qty}</span><button className="grid size-12 place-items-center" onClick={() => setQty(qty + 1)}><Plus /></button></div><Button className="h-12 flex-1 rounded-full bg-[#173a2b] text-white" onClick={() => { add(product, qty); go('cart') }}>Add to bag · ₹{product.price * qty}</Button></div></div></main> }

function Cart({ cart, total, go, change }: { cart: CartItem[]; total: number; go: (v: View) => void; change: (id: string, d: number) => void }) { return <main className="mx-auto max-w-[1200px] px-5 py-16 lg:px-14 lg:py-24"><p className="mb-4 text-[11px] font-bold uppercase tracking-[0.3em] text-[#b7663a]">Your bag</p><h1 className="font-serif text-6xl">Good choices.</h1>{cart.length ? <div className="mt-14 grid gap-12 lg:grid-cols-[1.2fr_.8fr]"><div className="flex flex-col gap-6">{cart.map((item) => <div key={item.id} className="flex gap-5 border-b border-[#173a2b]/15 pb-6"><div className="relative size-28 overflow-hidden rounded-2xl"><Image src={item.image} alt={item.name} fill className="object-cover"/></div><div className="flex flex-1 justify-between"><div><h2 className="font-serif text-2xl">{item.name}</h2><div className="mt-4 flex items-center rounded-full border border-[#d8c5a9]"><button className="grid size-8 place-items-center" onClick={() => change(item.id, -1)}><Minus /></button><span className="w-7 text-center text-sm">{item.quantity}</span><button className="grid size-8 place-items-center" onClick={() => change(item.id, 1)}><Plus /></button></div></div><b>₹{item.price * item.quantity}</b></div></div>)}</div><div className="h-fit rounded-[1.5rem] bg-[#173a2b] p-8 text-white"><h2 className="font-serif text-3xl">Order summary</h2><div className="mt-7 flex justify-between text-white/70"><span>Subtotal</span><span>₹{total}</span></div><div className="mt-3 flex justify-between text-white/70"><span>Shipping</span><span>{total >= 599 ? 'Free' : '₹60'}</span></div><div className="my-7 border-t border-white/20 pt-5 flex justify-between text-xl font-bold"><span>Total</span><span>₹{total >= 599 ? total : total + 60}</span></div><Button onClick={() => go('checkout')} className="h-14 w-full rounded-full bg-[#f1cf8a] text-[#173a2b] hover:bg-[#e7bd65]">Continue to checkout <ArrowRight data-icon="inline-end" /></Button></div></div> : <div className="py-20 text-center"><p className="text-[#65756d]">Your bag is waiting for something delicious.</p><Button onClick={() => go('shop')} className="mt-6 rounded-full bg-[#173a2b] text-white">Shop snacks</Button></div>}</main> }

function Checkout({ total, confirmed, setConfirmed, go }: { total: number; confirmed: boolean; setConfirmed: (v: boolean) => void; go: (v: View) => void }) { return <main className="mx-auto max-w-[1000px] px-5 py-16 lg:px-14 lg:py-24">{confirmed ? <div className="mx-auto max-w-xl py-20 text-center"><div className="mx-auto grid size-16 place-items-center rounded-full bg-[#b7663a] text-white"><Check /></div><p className="mt-7 text-[11px] font-bold uppercase tracking-[0.3em] text-[#b7663a]">Order confirmed</p><h1 className="mt-4 font-serif text-6xl">Good things are coming.</h1><p className="mt-6 leading-7 text-[#65756d]">Your demo order is confirmed. Razorpay can be connected here later without changing the storefront flow.</p><Button onClick={() => go('orders')} className="mt-9 rounded-full bg-[#173a2b] text-white">Track order <ArrowRight data-icon="inline-end" /></Button></div> : <><p className="mb-4 text-[11px] font-bold uppercase tracking-[0.3em] text-[#b7663a]">Demo checkout</p><h1 className="font-serif text-6xl">Almost there.</h1><form className="mt-14 grid gap-10 lg:grid-cols-[1fr_.6fr]" onSubmit={(e) => { e.preventDefault(); setConfirmed(true) }}><div className="flex flex-col gap-5"><h2 className="font-serif text-3xl">Delivery details</h2>{['First name','Last name','Email address','Address','City & pincode'].map((label) => <label key={label} className="text-sm font-semibold">{label}<input required className="mt-2 w-full rounded-xl border border-[#d8c5a9] bg-transparent px-4 py-3 font-normal outline-none focus:border-[#b7663a]" placeholder={label === 'Email address' ? 'you@example.com' : ''} /></label>)}<Button className="mt-3 h-14 rounded-full bg-[#173a2b] text-white">Place demo order · ₹{total >= 599 ? total : total + 60}</Button></div><div className="h-fit rounded-[1.5rem] bg-[#f3eadc] p-7"><h2 className="font-serif text-2xl">Payment</h2><p className="mt-4 text-sm leading-6 text-[#65756d]">Demo checkout only. No payment will be collected.</p></div></form></>}</main> }

function Account({ go }: { go: (v: View) => void }) { return <main className="mx-auto max-w-[1000px] px-5 py-16 lg:px-14 lg:py-24"><p className="mb-4 text-[11px] font-bold uppercase tracking-[0.3em] text-[#b7663a]">Your account</p><h1 className="font-serif text-6xl">Welcome back.</h1><div className="mt-14 grid gap-5 md:grid-cols-2"><button onClick={() => go('orders')} className="rounded-[1.5rem] bg-[#173a2b] p-8 text-left text-white"><PackageCheck className="text-[#f1cf8a]" /><h2 className="mt-12 font-serif text-3xl">Orders & tracking</h2><p className="mt-2 text-white/60">See where your good snacks are.</p></button><div className="rounded-[1.5rem] border border-[#d8c5a9] p-8"><CircleUserRound className="text-[#b7663a]" /><h2 className="mt-12 font-serif text-3xl">Sign in</h2><p className="mt-2 text-[#65756d]">Demo account UI ready for backend integration.</p></div></div></main> }
function Orders({ go }: { go: (v: View) => void }) { return <main className="mx-auto max-w-[1000px] px-5 py-16 lg:px-14 lg:py-24"><p className="mb-4 text-[11px] font-bold uppercase tracking-[0.3em] text-[#b7663a]">Order tracking</p><h1 className="font-serif text-6xl">On its way.</h1><div className="mt-14 rounded-[1.5rem] bg-[#f3eadc] p-8"><div className="flex justify-between"><div><p className="text-sm text-[#65756d]">Order #MR-1042</p><h2 className="mt-2 font-serif text-3xl">Himalayan Salt & Pepper</h2></div><span className="rounded-full bg-[#173a2b] px-4 py-2 text-xs text-white">Out for delivery</span></div><div className="mt-12 grid gap-8 border-t border-[#173a2b]/15 pt-8 md:grid-cols-3">{['Order placed','Roasted & packed','Out for delivery'].map((s, i) => <div key={s} className="flex gap-3"><span className={`grid size-8 place-items-center rounded-full ${i === 2 ? 'bg-[#b7663a] text-white' : 'bg-[#173a2b] text-white'}`}>{i + 1}</span><div><b>{s}</b><p className="mt-1 text-sm text-[#65756d]">{i === 2 ? 'Arriving today' : 'Complete'}</p></div></div>)}</div></div><Button onClick={() => go('shop')} className="mt-8 rounded-full bg-[#173a2b] text-white">Shop more snacks</Button></main> }
function Footer({ go }: { go: (v: View) => void }) { return <footer className="bg-[#173a2b] px-5 py-16 text-white lg:px-14"><div className="mx-auto grid max-w-[1440px] gap-12 md:grid-cols-[1.5fr_1fr_1fr_1.4fr]"><div><div className="font-serif text-3xl">MR Makhana</div><p className="mt-8 max-w-xs leading-7 text-white/60">Premium roasted makhana for the snack breaks that make your day better.</p></div><div><h3 className="mb-5 text-[11px] font-bold uppercase tracking-[0.25em] text-[#f1cf8a]">Explore</h3><div className="flex flex-col gap-3 text-white/70"><button className="text-left" onClick={() => go('shop')}>Shop all</button><button className="text-left" onClick={() => go('home')}>Our story</button><button className="text-left" onClick={() => go('orders')}>Track order</button></div></div><div><h3 className="mb-5 text-[11px] font-bold uppercase tracking-[0.25em] text-[#f1cf8a]">Help</h3><div className="flex flex-col gap-3 text-white/70"><span>FAQs</span><span>hello@mrmakhana.in</span><span>Shipping & returns</span></div></div><div><h3 className="mb-5 text-[11px] font-bold uppercase tracking-[0.25em] text-[#f1cf8a]">A little promise</h3><p className="font-serif text-3xl leading-tight">No boring snacks.<br />No unnecessary stuff.</p></div></div><div className="mx-auto mt-14 max-w-[1440px] border-t border-white/15 pt-5 text-xs text-white/40">© 2026 MR Makhana · Made in India</div></footer> }
